# Book settings
title: deep learning for molecules & materials
author: Andrew D. White
logo: _static/images/logo.png
copyright: "2025"

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon                   : "favicon.png"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  extra_navbar              : <script async defer src="https://api.dmol.pub/latest.js"></script><noscript><img src="https://api.dmol.pub/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript> By <a href="https://x.com/andrewwhite01">Andrew White</a>
  extra_footer              : <a href="http://thewhitelab.org">thewhitelab.org</a> <div id="wh-modal"> <button class="wh-venti-button" aria-label="close modal" id="wh-modal-close">âœ•</button> <img id="wh-modal-img"> </div>  # Will be displayed underneath the footer.
  baseurl                   : "https://dmol.pub"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_repository_button     : true
  use_issues_button         : true  # Whether to add an "open an issue" button

  # Information about where the book exists on the web
repository:
  url                       : https://github.com/whitead/dmol-book  # Online location of your book

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""  # Binder seems to be broken often during link checks?

bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
   - sphinx.ext.intersphinx
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    intersphinx_mapping:
      Python 3: ['https://docs.python.org/3/', null]
      tensorflow: ['https://www.tensorflow.org/api_docs/python', 'https://github.com/mr-ubik/tensorflow-intersphinx/raw/master/tf2_py_objects.inv']
      matplotlib [stable]: ['https://matplotlib.org/stable/', null]
      numpy [stable]: ['https://numpy.org/doc/stable/', null]
      pandas [latest?]: ['https://pandas.pydata.org/docs/', null]
      scikit-learn [stable]: ['https://scikit-learn.org/stable/', null]
      scipy [latest]: ['https://docs.scipy.org/doc/scipy/reference/', null]
      jax [latest]: ['https://jax.readthedocs.io/en/latest/', null]
      seaborn [stable]: ['https://seaborn.pydata.org/', null]
      exmol [latest]: ['https://ur-whitelab.github.io/exmol/', null]
    myst_html_meta:
      "description lang=en": "Deep Learning for Molecules & Materials Book"
      "property=og:locale": "en_US"
      "twitter:card": "summary"
      "twitter:description": "Deep Learning for Molecules & Materials Book"
      "twitter:title": "dmol.pub ðŸ“–"
      "twitter:image": "https://dmol.pub/_static/logo.png"
      "twitter:site": "@andrewwhite01"

only_build_toc_files        : true
exclude_patterns          : ['livecomj/*', 'dl/Equivariant.ipynb', 'dl/attention.ipynb', 'dl/VAE.ipynb', 'dl/Hyperparameter_tuning.ipynb', 'dl/pretraining.ipynb', 'dl/molnets.ipynb', 'applied/MolGenerator.ipynb', 'applied/e3nn_traj.ipynb', 'data/*', 'package/*', '_buid', '*.ipynb_checkpoints', '.venv', '.venv/*' ]
execute:
  timeout: -1
  execute_notebooks: force

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
