name: check-book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        conda install -c conda-forge pygraphviz
        cd package && python -m pip  --no-cache-dir install .
        pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
    - name: Check pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
    - name: Build the book
      run: env TF_CPP_MIN_LOG_LEVEL=3 jupyter-book build -n .
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.2.0
      continue-on-error: true
      id: lc
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
          args: --verbose --exclude rdkit.org/xml --max-redirects 100 --no-progress  _build/html/dl/**/*.html _build/html/ml/**/*.html _build/html/applied/**/*.html _build/html/*.html
          fail: true
