name: check-book

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        conda install -c conda-forge rdkit pygraphviz
        python -m pip install --no-cache-dir -r requirements.txt
    - name: Check pre-commit
      run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
    - name: Build the book
      run: env TF_CPP_MIN_LOG_LEVEL=3 jupyter-book build -n .
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      id: lc
      with:
          args: --verbose --no-progress  _build/dl/**/*.html _build/ml/**/*.html _build/applied/**/*.html _build/intro.html
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
